### ISSUE TITLE
Combine focus state tokens

### ISSUE THREAD

**Issue by petemill** [brave-experiments/leo#35]
```
 --effect-focus-state-0: -1px -1px 4px 2px rgba(255, 71, 36, 0.75);
  --effect-focus-state-1: 1px 1px 4px 2px rgba(95, 103, 215, 0.75);
  --effect-focus-state-2: 0px 0px 0px 1.7000000476837158px rgba(255, 255, 255, 0.75);
```

should be `effect-focus-state`.

Button should use this style as should the [upcoming collapsible](https://github.com/brave-experiments/leo/pull/27)

**Comment by petemill** [comment]
Should note that button's css uses the shadows in a different order than the tokens are defined in variables.css. We should check if the different layering causes visual changes @aguscruiz

**Comment by aguscruiz** [comment]
Ok yeah, let's see how it looks. Should I test it out in css by myself or will this be available in a Storybook somewhere?
